name: CI

on:
  push:
    branches:
      - staging
jobs:
  build:
    name: Debug Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.8.1'
          
      - run: flutter pub get
      - run: flutter analyze .
      - run: flutter test
      - run: flutter build apk --debug
      - name: Push to Development
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*"
          tag: dev-1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
